source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FBPLUGIN_Example' do
    pod "FBPLUGIN", :path => '../'


target 'FBPLUGIN_Tests'do
    inherit! :search_paths
    
    
end

end
