#source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
#
#target 'FBPLUGIN_Example' do
#  pod 'FBPLUGIN', :path => '../'
#end
#
#target 'FBPLUGIN_Tests' do
#  pod 'FBPLUGIN', :path => '../'
#
#end

use_frameworks!

target 'FBPLUGIN_Example' do
    pod 'FBPLUGIN', :path => '../'
    
    target 'FBPLUGIN_Tests' do
        inherit! :search_paths
        
    end
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end