source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FBPLUGIN_Example', :exclusive => true do
  pod "FBPLUGIN", :path => "../"
end

target 'FBPLUGIN_Tests', :exclusive => true do
  pod "FBPLUGIN", :path => "../"

  
end
